# Generated by Django 5.2.4 on 2025-07-03 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Becario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('legajo', models.CharField(help_text='Número de legajo único del becario.', max_length=20, unique=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('incidencia', models.BooleanField(default=False, help_text='Marcar si el registro tuvo un cierre automático o irregular.')),
                ('observaciones', models.TextField(blank=True, help_text='Detalles sobre la incidencia.', null=True)),
                ('becario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_horarios.becario')),
            ],
        ),
    ]
